# Generated by Django 2.0.1 on 2018-01-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Enter your name here')),
                ('occupation', models.CharField(max_length=30, verbose_name='What do you do?')),
                ('occupation_why', models.CharField(max_length=30, verbose_name='Why do you like you work?')),
                ('contact', models.EmailField(max_length=250)),
                ('memes', models.CharField(max_length=20)),
            ],
        ),
    ]
