# Generated by Django 2.0.1 on 2018-01-27 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_author_blog_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
